### ISSUE TITLE
Please add a release for 9.5 LTS

### ISSUE THREAD

**Issue by elmar-hinz** [FriendsOfTYPO3/extension_builder#187] opened 2018-12-16 09:52 UTC
The current master branch identifies as 9.10.0 in the BE but is not compatible with LTS 9.5 any more. It does not even save.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function EBT\ExtensionBuilder\Configuration\ExtensionBuilderConfigurationManager::getWiringEditorSmd(), 1 passed and exactly 2 expected | ArgumentCountError thrown in file /var/www/html/typo3conf/ext/extension_builder/Classes/Configuration/ExtensionBuilderConfigurationManager.php in line 533.

**Comment by nicodh** [comment] 2018-12-16 13:00
Can't reproduce this. I debugged the getWiringEditorSmd call and it gest 2 parameter passed as expected.
I added a release 9.10 to enable specific tagging if needed somewhen...

**Comment by elmar-hinz** [comment] 2018-12-16 13:20
I discovered this related issue: https://github.com/FriendsOfTYPO3/extension_builder/issues/178

I confirm it. I got the extension builder running for 9.5 LTS by manually editing the extension builder like described by the user qbadev.

My setup is a fresh installation of TYPO3 9.5. I checked out the TYPO3 sources from Github. If you want fully reproduce my setup you may use my docker container version v9lts.b and use the instructions given here: 

https://hub.docker.com/r/elmarhinz/typo3.docker-development

Also notice: https://stackoverflow.com/questions/53801050/which-version-of-the-extension-builder-is-working-for-typo3-9-5-lts

**Comment by nicodh** [comment] 2018-12-22 13:54
Fixed with #188

**Closed by nicodh** 2018-12-22 13:54 UTC
Labels: Needs feedback
