### ISSUE TITLE
 Support typo3 v8.7

### ISSUE THREAD

**Issue by Shleif91** [FriendsOfTYPO3/extension_builder#39] opened 2017-04-21 14:15 UTC
Good afternoon! Does your extension support version 8.7 and, if so, how do I configure the extension?
After installation, added a line to root composr.json `"EBT\\ExtensionBuilder\\": "typo3conf/ext/extension_builder/Classes/"`, because there was an error in the backend 
`Could not analyse class: "EBT\ExtensionBuilder\Controller\BuilderModuleController" maybe not loaded or no autoloader? Class EBT\ExtensionBuilder\Controller\BuilderModuleController does not exist`

Now, a white sheet and 500 error

**Comment by nicodh** [comment] 2017-04-21 15:17
If you install ExtensionBuilder with composer there should be no need to add any extra stuff for auto loading. Maybe you try running composer dump-autoload and have a look into the generated autoload files.

**Comment by nicodh** [comment] 2017-05-05 19:49
Can I close this?

**Comment by christian-forgacs** [comment] 2017-05-23 08:14
@nicodh the issue is in you ext_emconf.php (take a look: http://insight.helhum.io/post/130876393595/how-to-configure-class-loading-for-extensions-in)

In some reasons i can confirm, that the autoload configuration at composer.json is not enough. If i install a extension with requirements, the requirements without the ext_emconf.php entries which one not installed, TYPO3 throws this error. With the configuration in ext_emconf.php it works.

**Comment by nicodh** [comment] 2017-05-23 08:22
hmm, that's strange. An autoload section should only be required in case you have some "extra" Classes which not reside in the standard Classes folder.
If you look for example at https://github.com/georgringer/news/blob/master/ext_emconf.php there is no autoload section either...

**Comment by liayn** [comment] 2017-05-23 08:36
To clarify things: We are talking CMS v8 here. So we do not need any autoloading information in emconf at all. (same as CMS v7)
It does not matter how you install TYPO3 (composer based or not).

As far as I can tell the extension_builder composer.json is perfectly fine.

I suggest to run the dump-autoload functionality in the install tool or run the according composer command.
(just in case: make sure to remove any thing in the `typo3conf/autoload/` folder)

**Comment by christian-forgacs** [comment] 2017-05-23 08:49
When its not needed required to use the ext_emconf.php for TYPO3 v7 and v8 pleas tell my why I can reproduce the same issue for a few extensions with the posted workflow but if i add the autoload configuration in ext_emconf it works..? :confused:

**Comment by liayn** [comment] 2017-05-23 09:06
What is your workflow? Please describe it in a step-by-step manner, thanks.

**Comment by christian-forgacs** [comment] 2017-05-23 09:12
1. Download and install via get.typo3.org/8
2. Install TYPO3
3. Create a Test-Extension with following depends configuration:
3.1 array( 'extbase' => '8.7.0', 'fluid' => '8.7.0', 'typo3' => '8.7.0', 'recycler' => '', 'dce' => '', 'mask' => '', 'realurl' => '', 'cs_seo' => '', ),
3.1.1 Currently I've only test with this configuration not with extension_builder but I can test it with extension_builder too in a few days... I've currenty not the problem with extension_builder but I know the issue from other extensions
4. Download the current extension list in extension manager via get extensions (I have not update via the update button, only over initial switch to "get extension")
5. Install the test extension which download the extensions from depends array
6. Error throws (class not found in my case from dce extension)
7. Delete autoload folder in typo3conf
8. Try reinstall the test extension
9. It works

**Comment by liayn** [comment] 2017-05-23 09:18
ad 3.1)
# The dependencies on `extbase` and `fluid` are completely useless since v6.2, since they are mandatory system extensions anyway and are always there (and loaded pretty early).
# Always specify a proper version range for dependencies: `8.7.0-8.7.99` Do not leave them empty or halfbaked

ad 8) and 9)
This rather looks like a core bug then. Autoloading information should be regenerated whenever an extension is added/removed.

Please add this report to forge.typo3.org we have to deal with that there. This is for sure the wrong place here.

**Comment by christian-forgacs** [comment] 2017-05-23 09:34
Sorry for that. I saw the issue and thought I can help because I can reproduce it with other extensions and can fix it with the changes in ext_emconf.php

But you're right, its looks like a core bug... Here the created issue in TYPO3 forge: https://forge.typo3.org/issues/81311

**Comment by christian-forgacs** [comment] 2017-05-23 09:45
@nicodh is it possible that the TER version of the extension builder is not supported for v8? Because the version in TER is 7.6.18 not 8.6.0 which is in master branch...? Perhaps this is the issue from @Shleif91

**Comment by liayn** [comment] 2017-05-23 09:49
@christian-forgacs As you can see at
https://typo3.org/extensions/repository/view/extension_builder
`TYPO3 (7.6.0 - 7.6.99)`

And here on github there are branches:
https://github.com/FriendsOfTYPO3/extension_builder/tree/7.6
https://github.com/FriendsOfTYPO3/extension_builder/tree/master

**Comment by DanielRuf** [comment] 2017-07-15 15:04
It would be great to get some stable releases as some projects prefer stable and have a constraint to only allow stable packages.

Currently there are just the (unstable) dev branches.

**Comment by nicodh** [comment] 2017-07-16 07:30
But it is a developer extension. There is no need to install it in a 
production system.

Only the generated extensions should be deployed...

Or what does your workflow look like?

Regards,

Nico


Am 15.07.17 um 17:04 schrieb Daniel Ruf:
>
> It would be great to get some stable releases as some projects prefer 
> stable and have a constraint to only allow stable packages.
>
> Currently there are just the (unstable) dev branches.
>
>

**Comment by DanielRuf** [comment] 2017-07-16 09:59
@nicodh it's easier to have a lock file and a specific version of the extension. Other dev dependencies for composer also have tagged releases. It's just a DX thing. I could install it but missed releases ;-)

**Comment by fnagel** [comment] 2017-07-31 17:36
Same issue here, using following composer.json:

````
{
	"repositories": [
		{
			"type": "composer",
			"url": "https://composer.typo3.org/"
		},
		{
			"type": "package",
			"package": {
				"name": "typo3/extension-builder",
				"version": "dev-master",
			  	"type": "typo3-cms-extension",
				"source": {
					"url": "https://github.com/FriendsOfTYPO3/extension_builder.git",
					"type": "git",
					"reference": "master"
				}
			}
		}
	],
	"require": {
	  	"php": "^7.0",
	  	"typo3/cms": "~8.7"
	},
	"require-dev": {
		"typo3/extension-builder": "dev-master"
	},
	"extra": {
		"typo3/cms": {
			"cms-package-dir": "{$vendor-dir}/typo3/cms",
			"web-dir": "web"
		}
	}
}

````

Adding this works for me:

````
"autoload-dev": {
	"psr-4": {
		"EBT\\ExtensionBuilder\\": "web/typo3conf/ext/extension_builder/Classes/",
		"PhpParser\\": "web/typo3conf/ext/extension_builder/Resources/Private/PHP/PHP-Parser/lib/PhpParser/"
	}
},
````

Is using a custom composer package the wrong way to add extension builder?

**Comment by DanielRuf** [comment] 2017-07-31 18:01
A normal require should be enough to get it in the backend and enable it.

**Comment by fnagel** [comment] 2017-07-31 18:29
@DanielRuf Works as expected. Thanks! Not sure why I did it the custom package way.

**Closed** 2017-08-06 20:32 UTC
Labels: Needs feedback
