### ISSUE TITLE
Blank Domain Modelling v10-compatibility

### ISSUE THREAD

**Issue by loisfm** [FriendsOfTYPO3/extension_builder#309] opened 2020-07-30 14:58 UTC
Hi

For my Typo3 installation (v10.4) I have installed the extension_builder from the branch v10-compatibility. In the Domain Modelling page, I only saw a blank page. When I tried to solve the problem, I found that for the class "yui-layout-doc" a style of height: 0px; was specified.

As soon as you enter a higher height the Domain Modelling Mask will appear.

Greetings

**Comment by liayn** [comment] 2020-07-31 09:09
Without having tested this, I presume some JS error causes the hight calculation to fail.

**Comment by simonschaufi** [comment] 2020-07-31 13:19
This works without any problems on my machine.

**Comment by Flimmerkiste** [comment] 2020-07-31 13:27
I just ran into the same issue. Maybe this issue was introduced with one of the last commits? This worked a few days ago for me as well, but I have since then run a `composer update`, which also update the Extension Builder. I'm currently on the most recent commit from the `v10-compatibility` branch.

**Comment by simonschaufi** [comment] 2020-07-31 13:36
Nothing happened recently in this area of the code. Which browser are you using?

**Comment by loisfm** [comment] 2020-07-31 13:38
Are you using Typo3 v10.4.6?
Because on Typo3 v10.4.5 it works fine, but for Typo3 v10.4.6 the height is set to 0.

**Comment by simonschaufi** [comment] 2020-07-31 13:57
yes, v10.4.5

**Comment by loisfm** [comment] 2020-07-31 14:13
I think so, too.
I will work with the Typo3 v10.4.5 until this bug is fixed.

Thank you guys for your incredible work.

**Comment by Flimmerkiste** [comment] 2020-07-31 14:32
Yes, 10.4.6 seems to have caused this. Thanks for the quick replies you guys!

**Comment by liayn** [comment] 2020-07-31 14:34
May be related to https://review.typo3.org/c/Packages/TYPO3.CMS/+/65103

**Comment by liayn** [comment] 2020-08-02 18:13
Confirmed. The class `typo3-fullDoc` has been removed, hence the 100% width/height is gone. The whole Backend module HTML and CSS needs to be adjusted to match v10's expectations.

**Comment by liayn** [comment] 2020-09-25 19:00
Has been fixed with #310

**Closed by liayn** 2020-09-25 19:00 UTC
Labels: bug
