### ISSUE TITLE
Extension could not be saved: Could not create public resources folder

### ISSUE THREAD

**Issue by fritzdacat** [FriendsOfTYPO3/extension_builder#23] opened 2017-03-12 16:31 UTC
I get this error when saving an extension again:
<img width="413" alt="bildschirmfoto 2017-03-12 um 17 29 47" src="https://cloud.githubusercontent.com/assets/5744779/23833726/ea229e3e-0749-11e7-945c-186b36a83f6a.png">
TYPO3 8.6.1

**Comment by nicodh** [comment] 2017-03-12 17:09
Duplicate of #21

**Closed by nicodh** 2017-03-12 17:09 UTC
