### ISSUE TITLE
Backend error when accidentially linking two properties

### ISSUE THREAD

**Issue by criwe** [FriendsOfTYPO3/extension_builder#295] opened 2020-06-18 18:22 UTC
Hi!

When trying to connect to model object via relation (doesn´t matter which kind) an save the extension, I get the following error:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of EBT\ExtensionBuilder\Domain\Model\DomainObject\Relation\AbstractRelation::getForeignModel() must be an instance of EBT\ExtensionBuilder\Domain\Model\DomainObject, null returned | TypeError thrown in file typo3conf/ext/extension_builder/Classes/Domain/Model/DomainObject/Relation/AbstractRelation.php in line 95`

removing the relation and everything work fine so far.

TYPO3: 10.4.3
Extension builder: the v10-compatibility

Best,
Christoph

**Comment by DavidBruchmann** [comment] 2020-06-18 19:27
Yes I can confirm there problems, never verified it very detailed.  
As I had different types of relations anyway Extension Builder was not useful for that project in general.

**Comment by simonschaufi** [comment] 2020-06-18 20:54
Thanx for testing the v10 branch. I will take care of a fix.

**Comment by simonschaufi** [comment] 2020-06-19 19:14
@criwe I tried to reproduce it. Does your relation have a wire to another object or not? Whenever I have a wire, I get a proper DomainObject model back in that method. It would help to see a screenshot of what you are doing.

**Comment by criwe** [comment] 2020-06-21 15:51
Hi Simon,
thanks for investigating the error. Here a screenshot:

![Zwischenablage02](https://user-images.githubusercontent.com/7531138/85228898-ab89b480-b3e6-11ea-8d61-734898736ab3.jpg)

It doesn´t matter which type (1:n, 1:1...) i choose. When I save, the error message is thrown.
Hope that helps!
Best,
Christoph

**Comment by simonschaufi** [comment] 2020-06-21 21:48
Thanx, that helps. The wire needs to go to the top bubble. Did that produce a correct php code in previous versions? I have never seen that myself. I always connect relation to model and not relation to relation.

**Comment by DavidBruchmann** [comment] 2020-06-22 04:20
![image](https://user-images.githubusercontent.com/999146/85248179-48496200-b47a-11ea-87dd-7a2003f4b182.png)

As property there is a single-text-field added in the model.

**Comment by DavidBruchmann** [comment] 2020-06-22 04:26
Same scenario, just extending the news-model instead of tt_content 
![image](https://user-images.githubusercontent.com/999146/85248489-22708d00-b47b-11ea-9a8b-4e528181d650.png)

**Comment by simonschaufi** [comment] 2020-06-22 08:38
@DavidBruchmann your error is different than the one from @criwe . please don't mix 2 errors in one issue.

**Comment by DavidBruchmann** [comment] 2020-06-22 08:47
Thanks, @simonschaufi  see #302

**Comment by criwe** [comment] 2020-06-27 15:49
@simonschaufi omg, you are right, when connecting with the top bubble, saving works fine. That should be the right way!
Maybe the errormessage when connecting two relations should be a bit clearified.

**Comment by liayn** [comment] 2020-09-25 19:03
So actually the fix would be to simply disallow connecting two properties directly, which obviously makes no sense.

**Comment by simonschaufi** [comment] 2021-06-16 23:22
Closing this as duplicate of #400

**Closed by simonschaufi** 2021-06-16 23:22 UTC
Labels: bug
