### ISSUE TITLE
Exception when saving

### ISSUE THREAD

**Issue by butu** [FriendsOfTYPO3/extension_builder#355] opened 2021-02-21 17:01 UTC
**Describe the bug**
When I save an Extension Created in TYPO3 8 in TYPO310 Extension-Builder I get this Exception:

Argument 2 passed to EBT\ExtensionBuilder\Configuration\ExtensionBuilderConfigurationManager::getExtensionSettings() must be of the type string, null given, called in /app/public/typo3conf/ext/extension_builder/Classes/Service/ExtensionSchemaBuilder.php on line 295

**Expected behavior**
I want to open the Extension save it and TYPO3 10 compatible code should be generated.

**TYPO3 Version**
10

**Extension Builder Version:**
Git-branch

Thank you! :)

**Comment by nicodh** [comment] 2021-02-21 21:31
That's probably an error with the extension path,caused by extensions in ext/typo3conf/ext/ in composer mode and .
Please have a look at https://github.com/FriendsOfTYPO3/extension_builder/blob/v10-compatibility/Documentation/User/Index.rst
which is not yet public...

**Comment by AlexanderKoe** [comment] 2021-03-15 14:28
Found this bug in ExtensionBuilderConfigurationManager.php line 245
$settings = file_get_contents($codeTemplateRootPaths[0] . 'Configuration/ExtensionBuilder/settings.yamlt');
shoud be "settings.yaml", right?

After fixing this I run into the same bug described here. My TYPO3 is not and never has been in composer mode.
Also tried to work on a extension started in TYPO3 8 now in TYPO3 10. Latest extension_builder v10 compatibilty release.

I tried to debug this and found out getExtensionSettings() is called twice while saving. The first time the storage path is set correct, the second time it is empty. Maybe this helps for further debugging

I was able to write the extension by manually set the storage path here (absolute path). This is a short fix for other people running into the same problem at the moment.

**Comment by liayn** [comment] 2021-03-15 14:48
> shoud be "settings.yaml", right?

No this is correct, the file `Resources/Private/CodeTemplates/Extbase/Configuration/ExtensionBuilder/settings.yamlt` exists.

**Comment by liayn** [comment] 2021-03-16 16:25
maybe related #380

**Comment by benwick** [comment] 2021-03-23 20:07
> That's probably an error with the extension path,caused by extensions in ext/typo3conf/ext/ in composer mode and .
> Please have a look at https://github.com/FriendsOfTYPO3/extension_builder/blob/v10-compatibility/Documentation/User/Index.rst
> which is not yet public...

Mh... I really don't understand this. To het a path repository to work with both extension builder and composer, you have to add two entries:

```
    "repositories": [
        {
            "type": "path",
            "url": "./extensions/extension_name"
        },
        {
            "type": "path",
            "url": "./extensions"
        }
    ]
```

The first you need to install the extension with composer. The second to load the extension with the builder.

**Comment by simonschaufi** [comment] 2021-03-23 21:14
@benwick no, this is wrong, you should only have one path. use the second one. the path to the extension will be detected by composer automatically.

**Comment by simonschaufi** [comment] 2021-06-16 16:24
Closing this as not reproducible

**Closed by simonschaufi** 2021-06-16 16:24 UTC
Labels: Needs feedback

**Comment by neufeind** [comment] 2021-07-20 16:14
I have the same problem opening and simply trying to save an old extension created with BE. I'm using non-composer-mode for both the TYPO3 v10 as well as (of course) the extension I'm trying to create.

**Comment by neufeind** [comment] 2021-07-20 16:19
could we maybe add the default-value for a storagePath in getStoragePath as well, like in another place? or a different way to set the default?

    public function getStoragePath(): ?string
    {
        return $this->storagePath ?? Environment::getPublicPath() . '/typo3conf/ext/';
    }

**Comment by simonschaufi** [comment] 2021-07-20 16:48
@neufeind You can come up with a PR and a test case and I will take care of it.
