### ISSUE TITLE
Controller not found

### ISSUE THREAD

**Issue by eliteSchwein** [FriendsOfTYPO3/extension_builder#414] opened 2021-07-02 07:37 UTC
**Describe the bug**
Extension Builder doesnt load with the Error Message:

Class ExtensionBuilder\Controller\EBT\ExtensionBuilder\Controller\BuilderModuleControllerController does not exist. Reflection failed.

**To Reproduce**
1. Clone the Repo
2. Activate Extension Builder
3. Go on the Extension Builder Page

**Expected behavior**
Working extension

**Screenshots**
![image](https://user-images.githubusercontent.com/39838619/124238575-0b965900-db19-11eb-975c-570037b38a93.png)

**TYPO3 Version**
10.4.17

**Extension Builder Version:**
Git-Branch

**Comment by simonschaufi** [comment] 2021-07-02 09:01
I highly recommend using composer as in future TYPO3 versions it will probably became the standard. With composer I don't have any problem.

Instead of fetching the latest release, fetch `dev-master`

**Comment by eliteSchwein** [comment] 2021-07-02 09:05
i am using master, composer wont install extension_builder because i am on typo3 10

**Comment by liayn** [comment] 2021-07-02 09:47
> 
> 
> i am using master, composer wont install extension_builder because i am on typo3 10

I don't understand what you mean here.

**Comment by DavidBruchmann** [comment] 2021-07-02 09:56
@eliteSchwein  This is from composer.json of the current master:
```
	"require": {
		"php": "^7.2",
		"ext-json": "*",
		"nikic/php-parser": "^4.10.4",
		"typo3/cms-backend": "^10.4.10"
	},
```
So it should be installable with TYPO3 10 as long as PHP is in Version 7.2 - 7.99 and "nikic/php-parser" can be fetched in the right version.
You've to install with `composer require friendsoftypo3/extension-builder:@dev` or  `composer require friendsoftypo3/extension-builder:dev-master`, else it will be tried to install another version.

**Comment by simonschaufi** [comment] 2021-07-02 10:42
Closing as this is not a bug that needs to be fixed.

**Closed by simonschaufi** 2021-07-02 10:42 UTC
